name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - ipywidgets==8.0.6
    - voici>=0.4.1,<0.5.0
    - jupyterlite-xeus-python>=0.8.0,<0.9.0
    - jupyterlab_widgets