name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlite-xeus-python >=0.9.1,<0.10.0
  - pip:
    - nbconvert<7.6.0
    - ipywidgets==8.0.6
    - voici>=0.4.5,<0.5.0
    - jupyterlite-xeus-python >=0.9.1,<0.10.0
    - jupyterlab_widgets